# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://www.pomodoros.com.br/")
    # 2 | setWindowSize | 763x586 |  | 
    self.driver.set_window_size(763, 586)
    # 3 | click | css=#section0 > .fp-tableCell |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#section0 > .fp-tableCell").click()
    # 4 | click | css=.icon-leg:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".icon-leg:nth-child(1)").click()
    # 5 | click | id=user_login |  | 
    self.driver.find_element(By.ID, "user_login").click()
    # 6 | click | id=user_login |  | 
    self.driver.find_element(By.ID, "user_login").click()
    # 7 | doubleClick | id=user_login |  | 
    element = self.driver.find_element(By.ID, "user_login")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 8 | type | id=user_login | foca | 
    self.driver.find_element(By.ID, "user_login").send_keys("foca")
    # 9 | type | id=user_pass | 931777 | 
    self.driver.find_element(By.ID, "user_pass").send_keys("931777")
    # 10 | click | css=.login-remember > label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".login-remember > label").click()
    # 11 | click | id=wp-submit |  | 
    self.driver.find_element(By.ID, "wp-submit").click()
  
